### ISSUE TITLE
Lightbox feature not compatible with Jquery Mobile

### ISSUE THREAD

**Issue by fatfantasma** [kthornbloom/Smoothproducts#19]
Hey,  I thought I would start a new thread on this issue.

The lightbox feature is not working with jquery mobile.  When you click on the large image nothing happens.  However, if I then back out of my page the lightbox shows the image for a couple of seconds then disappears.

I believe it has something to do with how you append the lightbox to 'body'

$('body').append('<div class="sp-lightbox" data-currenteq="'+currentThumb+'"><img src="' + currentImg + '"/></div>');

jquery mobile does several html enhancements that is incompatible in how your plugin operations.

**Comment by fatfantasma** [comment]
Hey Kevin,

I was able to resolve the issue by increasing the z-index to 1000 by overriding the .sp-lightbox class.  Once that was done it worked great in the jquery mobile framework.

.sp-lightbox {
    z-index: 1000 !important;
}

**Comment by kthornbloom** [comment]
Glad you got it sorted out! I've had to increase the z-index on some of my projects as well. Maybe i'll just update that in the plugin.
