### ISSUE TITLE
jquery problem 

### ISSUE THREAD

**Issue by testerzs** [kthornbloom/Smoothproducts#23]
Hi,
When I add  ` <script type="text/javascript" src="js/jquery-2.1.3.min.js"></script>` in my footer the Smoothproducts script is working but my menubar (navbar) is not working when I add "jquery-2.1.3.min.js"

See the differences:
http://demo.redloveappel.eu/p/p.html (with out "jquery-2.1.3.min.js" Smoothproducts is not working)

http://demo.redloveappel.eu/p/p1.html (with "jquery-2.1.3.min.js")

Hope that you can help me

**Comment by kthornbloom** [comment]
Hi, it's probably conflicting with some other JS on the page. You'll just need to debug by removing things until you find the problem!

**Comment by testerzs** [comment]
thanks I will check that
