### ISSUE TITLE
Trying to add zoom out on mouseout

### ISSUE THREAD

**Issue by Cozmoz** [kthornbloom/Smoothproducts#7]
Hi there,

I am trying to add a zoom out on mouseout function but it doesn't seem to be working, any help would be appreciated. I have currently added the following code after the existing zoom out function:

            $('.sp-large').mouseout(function() {
				$('div.sp-full-screen').remove();
				$('div.sp-zoom').remove();
            });

Thanks!

**Comment by kthornbloom** [comment]
Solved in version 2.0.0!
